### ISSUE TITLE
Demo site not working

### ISSUE THREAD

**Issue by mkantautas** [mastashake08/laravel-web-push#1]
Seems that your SSL certificate expired or sm other issue, thus demo push notifications are not testable.

**Comment by mastashake08** [comment]
OK I will fix tonight

*Jyrone Parker*
*Technical Consultant, *Technopreneur

*Never Let Limited Minds Limit Your Success*
*https://www.jyroneparker.com <http://www.jyroneparker.com> |
https://youtube.com/c/jyroneparker <https://youtube.com/c/jyroneparker>*
Twitter: @mastashake08

**Comment by MichaelNgugiN** [comment]
I cannot get the demo to work, I've run all the commands as described but web push still doesn't work.

**Comment by worgor** [comment]
have the same issue, nothing is pushed or shown! do i miss something or is it not available for localhost without https?

**Comment by brickgale** [comment]
+1 cloned, migrated, tinkered users but on the enable notifications page, it won't work. clicking enable notifications, calling save-subscription api endpoint, trigger an error (sqlstate error). and send notification doesn't do anything.

**Comment by mastashake08** [comment]
You have to have https OR disable the flags in your browser.
